"""SciDuck — A thin DuckDB layer for managing versioned scientific data."""

from .sciduckdb import (
    SciDuck,
    bulk_df_to_storage_rows,
    dataframe_to_storage_rows,
    _flatten_dict,
    infer_data_columns,
    _infer_duckdb_type,
    _numpy_dtype_to_duckdb,
    _python_to_storage,
    record_schema_mismatch,
    _storage_signature,
    storage_to_python,
    storage_to_python_column,
    unflatten_dict,
    value_to_storage_row,
    array_from_storage,
    count_nan_array_elements,
    count_null_list_elements,
    schema_keys_from_db,
)

__all__ = [
    "SciDuck",
    "schema_keys_from_db",
    "array_from_storage",
    "count_null_list_elements",
    "count_nan_array_elements",
    "_infer_duckdb_type",
    "_numpy_dtype_to_duckdb",
    "_python_to_storage",
    "storage_to_python",
    "storage_to_python_column",
    "infer_data_columns",
    "record_schema_mismatch",
    "_storage_signature",
    "value_to_storage_row",
    "dataframe_to_storage_rows",
    "bulk_df_to_storage_rows",
    "_flatten_dict",
    "unflatten_dict",
]
