/**
 * MathWorks MATLAB terminal integration.
 *
 * Detects whether the MathWorks VS Code extension is installed, opens the
 * MATLAB command window, and sends commands to it.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as vscode from 'vscode';
import { LogSink } from './sessionCore';

/**
 * Local wall-clock stamp as `yyyy-mm-dd HH:MM:SS.mmm`.
 *
 * Deliberately local time, not `toISOString()` (which is UTC): this stamp
 * exists to be subtracted from the generated script's own `script_start`
 * line and from scidb.log's timestamps, and both of those are local. A UTC
 * stamp would silently read as an hours-long dispatch.
 */
function formatStamp(d: Date): string {
  const p = (n: number, w = 2) => String(n).padStart(w, '0');
  return (
    `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ` +
    `${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}.` +
    `${p(d.getMilliseconds(), 3)}`
  );
}

/**
 * Check whether the MathWorks MATLAB extension is installed.
 */
export function isMatlabExtensionAvailable(): boolean {
  return vscode.extensions.getExtension('MathWorks.language-matlab') !== undefined;
}

/**
 * Whether a MATLAB terminal already exists in this VS Code session.
 *
 * A rough proxy for "MATLAB is connected" — the MathWorks extension has no
 * public API for actual readiness. Used by matlabConnectionGate.ts to tell
 * a genuine first-time "Run" click (which only starts MATLAB) apart from a
 * click after MATLAB is already up.
 */
export function isMatlabTerminalOpen(): boolean {
  return vscode.window.terminals.some(t => t.name === 'MATLAB');
}

/**
 * Send a command string to the MathWorks MATLAB terminal.
 *
 * The MathWorks pseudoterminal reliably routes short single-line sendText
 * payloads (e.g. typed-by-human commands) but silently drops the multi-line
 * script generated by scistack_gui.api.matlab_command — nothing appears in
 * the MATLAB terminal and the commands never reach the MATLAB engine. As a
 * result, addpath/configure_database/for_each never execute and any
 * breakpoint set on the target function never fires.
 *
 * We work around this by writing the full script to a temp ``.m`` file and
 * sendText-ing a one-line ``run('<path>')``. That single short call is
 * delivered reliably by the pseudoterminal.
 *
 * @returns true if the command was dispatched, false if the terminal is
 *          unavailable (caller falls back to clipboard).
 */
export async function runInMatlabTerminal(
  command: string,
  outputChannel?: LogSink,
  /**
   * A token unique to the calling session (`sessionCore.sessionSlug`), so
   * each database writes its own script file. With one fixed name, two
   * sessions dispatching close together raced: the second write landed
   * before the first `run('…')` read it, and one canvas ran the other's
   * script. Optional so the browser build and tests need not supply one.
   */
  sessionSlug?: string,
): Promise<boolean> {
  if (!isMatlabExtensionAvailable()) {
    return false;
  }

  try {
    // Dispatch timing. A short MATLAB run spent ~4.4s between the GUI
    // emitting the script and MATLAB's first scidb log line; none of that
    // window was attributable, because nothing on either side timestamped
    // it. These three deltas split the VS Code half (write / open command
    // window / sendText), and the wall-clock stamp on the sendText line
    // pairs with the generated script's own `[SciStack][timing]
    // script_start` stamp to measure everything in between — MATLAB
    // picking up the pseudoterminal input and parsing the script — which
    // neither side can see alone.
    const t0 = Date.now();

    // Stable per session (overwritten each invocation) so we don't clutter
    // the temp dir, but never shared between sessions — see `sessionSlug`.
    // `run` evaluates the script in the caller's workspace, so variables
    // defined in the script remain visible after it returns.
    //
    // MATLAB identifiers: the name must start with a letter and hold only
    // word characters, or `run` cannot resolve it as a script.
    const scriptPath = path.join(
      os.tmpdir(),
      sessionSlug ? `scistack_run_${sessionSlug}.m` : 'scistack_run.m',
    );
    fs.writeFileSync(scriptPath, command, 'utf-8');
    const tWritten = Date.now();
    outputChannel?.appendLine(
      `runInMatlabTerminal: wrote ${command.length}-char script to ${scriptPath} ` +
        `[timing] write=${tWritten - t0}ms`,
    );

    // The MathWorks extension provides this command to open the MATLAB
    // command window as an integrated terminal.
    await vscode.commands.executeCommand('matlab.openCommandWindow');
    const tOpened = Date.now();
    outputChannel?.appendLine(
      `runInMatlabTerminal: [timing] openCommandWindow=${tOpened - tWritten}ms`,
    );

    // Find the MATLAB terminal (created by the MathWorks extension).
    const terminal = vscode.window.terminals.find(t => t.name === 'MATLAB');
    if (!terminal) {
      outputChannel?.appendLine(
        'MathWorks extension found but MATLAB terminal not available.'
      );
      return false;
    }

    // MATLAB accepts forward slashes on Windows; converting avoids having
    // to escape backslashes inside the single-quoted string literal.
    const forMatlab = scriptPath.replace(/\\/g, '/');
    const runLine = `run('${forMatlab}');`;
    outputChannel?.appendLine(`runInMatlabTerminal: sendText ${runLine}`);
    terminal.sendText(runLine);
    terminal.show();
    const tSent = Date.now();
    outputChannel?.appendLine(
      `runInMatlabTerminal: [timing] sendText=${tSent - tOpened}ms, ` +
        `dispatch_total=${tSent - t0}ms, sent_at=${formatStamp(new Date(tSent))}`,
    );
    return true;
  } catch (err) {
    outputChannel?.appendLine(`Failed to send to MATLAB terminal: ${err}`);
    return false;
  }
}
