% Run this file from the Stroke-R01-Aim-2 project folder
%% Add code to path (points to src/ folder)
addpath(genpath(fileparts(fileparts(matlab.desktop.editor.getActiveFilename))));

%% Load config
configPath = fullfile('src','overground','config_Aim2.json');
config = jsondecode(fileread(configPath));

%% Dataset setup
root_load = config.PATHS.ROOT_LOAD;
schema = ["subject", "session", "speed", "trial", "cycle"];
db_root = 'C:\Users\mtillman\Datasets\Stroke Aim 2';
% delete(fullfile(db_root, 'data.db'));
scidb.configure_database(fullfile(db_root, 'data.db'), schema);
scidb.Log.set_level('DEBUG')

%% Load the assessment day GAITRite data
gaitritePathTemplate = '{subject}/Gaitrite/{session}/{subject}_{session}_GR_{speed}.xlsx';
gaitritePath = scifor.PathInput(gaitritePathTemplate, 'root_folder',root_load, 'name', 'gaitritePath');
subjects = ["SS03", "SS09", "SS10", "SS20", "SS21", "SS25", "SS27", "SS28", "SS32", "SS33"];
sessions = ["BL", "MID24", "POST24", "MO1FU", "MO3FU"];
speeds = ["FV", "SSV"];
scidb.for_each(@loadGaitRiteOneFile, ...
    struct('xlsx_file_path', gaitritePath, 'gaitRiteConfig', config.GAITRITE), ...
    {GAITRiteLoaded()}, ...
    subject=subjects, session=sessions, speed=speeds, ...
    distribute=true ...
);

%% Load the training day GAITRite data
gaitritePathTemplate = '{subject}/Gaitrite/TX/{session}/{subject}_{session}_GR_{speed}.xlsx';
gaitritePath = scifor.PathInput(gaitritePathTemplate, 'root_folder', root_load, 'name', 'gaitritePath');
% subjects = ["SS09", "SS10", "SS20", "SS21", "SS25", "SS28", "SS32"];

% speeds = ["SSV"];
% sessions = ["TX19"];
% subjects = ["SS09"];
sessions = ["TX4", "TX7", "TX10", "TX13", "TX16", "TX19", "TX22"];
scidb.for_each(@loadGaitRiteOneFile, ...
    struct('xlsx_file_path', gaitritePath, 'gaitRiteConfig', config.GAITRITE), ...
    {GAITRiteLoaded()}, ...
    subject=[], session=sessions, speed=[], ...
    distribute=true ...
);

%% Load Delsys
delsysPathTemplate = '{subject}/EMG/{session}/{subject}_EMG_{session}_{speed}{trial}.mat';
delsysPath = scifor.PathInput(delsysPathTemplate, 'root_folder', root_load, 'name', 'delsysPath');
scidb.for_each(@loadDelsysEMGOneFile, ...
    struct('mat_file_path', delsysPath), ...
    {DelsysLoaded()}, ...
    subject=[], session=[], speed=speeds, trial=[] ...
);

%% Filter Delsys
scidb.for_each(@filterDelsys, ...
    struct('delsysEMG', DelsysLoaded(), 'filterConfig', config.DELSYS_EMG.FILTER, 'Fs', config.DELSYS_EMG.SAMPLING_FREQUENCY), ...
    {FilteredDelsys()}, ...
    subject=[], session=[], speed=[], trial=[] ...
);

%% Load XSENS
xensPathTemplate = '{subject}/XSENS/{session}/{subject}_XSENS_{session}_{speed}-00{trial}.xlsx';
xsensPath = scifor.PathInput(xensPathTemplate, 'root_folder', root_load, 'name', 'xsensPath');
scidb.for_each(@loadXSENSOneFile, ...
    struct('xlsx_file_path', xsensPath, 'configNamesStruct', config.XSENS.COLUMN_NAMES), ...
    {XSENSLoaded()}, ...
    subject=[], session=[], speed=[], trial=[] ...
);

%% Filter XSENS
scidb.for_each(@filterXSENS, ...
    struct('loadedXSENS', XSENSLoaded(), 'filterConfig', config.XSENS.FILTER, 'Fs', config.XSENS.SAMPLING_FREQUENCY), ...
    {FilteredXSENS()}, ...
    subject=[], session=[], speed=[], trial=[] ...
);

%% Get time-synced frame numbers for Delsys
scidb.for_each(@getHardwareIndicesFromSeconds, ...
    struct('gaitriteTable', GAITRiteLoaded("seconds"), 'fs', config.DELSYS_EMG.SAMPLING_FREQUENCY), ...
    {DelsysFramesGaitEvents()}, ...
    subject=[], session=[], speed=[], trial=[] ...
);

%% Get time-synced frame numbers for XSENS
scidb.for_each(@getHardwareIndicesFromSeconds, ...
    struct('gaitriteTable', GAITRiteLoaded("seconds"), 'fs', config.XSENS.SAMPLING_FREQUENCY), ...
    {XSENSFramesGaitEvents()}, ...
    subject=[], session=[], speed=[], trial=[] ...
);

%% Load Delsys MVC data
% filenamesRegex = '(Left|Right)_(Ankle|Knee|Hip)_(Flexors|Extensors)\.mat';
mvcFolderTemplate = '{subject}/MVCs/{session}/{subject}_MVCs_{session}_';
mvcFolderPath = scifor.PathInput(mvcFolderTemplate, 'root_folder', root_load, 'name', 'mvcFolderPath');
scidb.for_each(@loadMVCOneSession, ...
    struct('mvcPath', mvcFolderPath, 'mvcConfig', config.DELSYS_EMG.MVC_MUSCLE_MAPPING), ...
    {MVCLoaded()}, ...
    subject=[], session=[] ...
);

%% Filter Delsys MVC data
scidb.for_each(@filterDelsys, ...
    struct('mvcData', MVCLoaded(), 'filterConfig', config.DELSYS_EMG.FILTER, 'Fs', config.DELSYS_EMG.SAMPLING_FREQUENCY), ...
    {FilteredMVC()}, ...
    subject=[], session=[] ...
);

%% Identify MVC
scidb.for_each( ...
);

%% Normalize Delsys EMG data
scidb.for_each(@normalizeAllDataToVisitValueNoTable, ...
    struct(), ...
    {NormalizedEMG()}, ...
    subject=[], session=[], trial=[] ...
);

%% Split XSENS data by gait cycle

%% Split Delsys data by gait cycle

%% Split GAITRite by gait cycle
scidb.for_each(@distributeGaitRiteDataToSeparateTableNoTable, ...
    struct('gaitriteTable', GAITRiteLoaded()), ...
    {GAITRiteLoadedCycle()}, ...
    subject=[], session=[], speed=[], trial=[], ...
    distribute=true ...
);

%% Downsample each gait cycle's data to 101 points: Delsys

%% Downsample each gait cycle's data to 101 points: XSENS

%% Get % gait cycle when peaks occur

%% Calculate the number of muscle synergies

%% Calculate area under the curve (AUC)

%% Calculate root mean square (RMS)

%% Calculate range of motion (ROM)

%% Match left and right gait cycles for symmetry analysis: XSENS
scidb.for_each(@matchCyclesNoTable, ...
    struct('inputData', CyclesXSENS()), ...
    {matchedCyclesXSENS()}, ...
    subject=[], session=[], trial=[] ...
);

%% Match left and right gait cycles for symmetry analysis: Delsys
scidb.for_each(@matchCyclesNoTable, ...
    struct('inputData', CyclesDelsys()), ...
    {matchedCyclesDelsys()}, ...
    subject=[], session=[], trial=[] ...
);

%% Calculate root mean squared error (RMSE)

%% Calculate cross-correlations

%% Calculate symmetry
scidb.for_each(@calculateLRSymmetryTwoVectorsNoTable, ...
    struct('v1', GAITRiteLoadedCycle("StepLengths_GR"), 'formulaNum', 6), ...
    {StepLengthSymmetry()}, ...
    subject=[], session=[], speed=[], trial=[], distribute=true ...
);

%% Convert L/R to U/A
uaConfig.SS09 = "L";
uaConfig.SS10 = "R";
uaConfig.SS20 = "L";
uaConfig.SS21 = "L";
scidb.for_each(@LRtoUA, ...
    struct('lr', GAITRiteLoadedCycle(), 'uaConfig', uaConfig), ...
    {UAStartFoot}, ...
    subject=[], session=[], speed=[], trial=[], as_table=true, distribute=true ...
);

%% Change in step length from baseline
sessionsExclBL = ["MID24", "POST24", "MO1FU", "MO3FU", "TX4", "TX7", "TX10", "TX13", "TX16", "TX19", "TX22"];
scidb.for_each(@meanChangeFromReference, ...
    struct('baseline', scidb.Fixed(GAITRiteLoadedCycle("StepLengths_GR"), session="BL"), 'value', GAITRiteLoadedCycle("StepLengths_GR")), ...
    {DeltaStepLength()}, ...
    as_table=false, ...
    subject=[], session=[], speed=[], where=UAStartFoot() == "A" ...
);

%% Change in step length symmetry from baseline
scidb.for_each(@meanChangeFromReference, ...
    struct('baseline', scidb.Fixed(StepLengthSymmetry(), session="BL"), 'value', StepLengthSymmetry()), ...
    {DeltaStepLengthSymmetry()}, ...
    as_table=false, ...
    subject=[], session=[], speed=[] ...
);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%% STATS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Step length Cohen's d
scidb.for_each(@computeCohensD, ...
    struct('v1', scidb.Fixed(GAITRiteLoadedCycle("StepLengths_GR"), session="BL"), 'v2', GAITRiteLoadedCycle("StepLengths_GR")), ...
    {StepLengthCohensD()}, ...
    subject=[], session=[], speed=[], where=UAStartFoot() == "A" ...
);

%% Step length symmetry Cohen's d
scidb.for_each(@computeCohensD, ...
    struct('v1', scidb.Fixed(StepLengthSymmetry(), session="BL"), 'v2', StepLengthSymmetry()), ...
    {StepLengthSymmetryCohensD()}, ...
    subject=[], session=[], speed=[] ...
);

%% 1 way ANOVA on each subject's step lengths

%% 1 way ANOVA on each subject's step length symmetry

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%% PLOTS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Step length
savePath = "Y:\LabMembers\MTillman\GitRepos\Stroke-R01-Aim-2\plots\allSubjectsAllSessions";
scidb.for_each(@plotPerSessionPerSubject, ...
    struct('inputVal', DeltaStepLength(), 'colName', 'DeltaStepLength', 'savePath', savePath), ...
    {}, ...
    speed=["FV"], as_table=true ...
);

%% Step length symmetry
savePath = "Y:\LabMembers\MTillman\GitRepos\Stroke-R01-Aim-2\plots\allSubjectsAllSessions";
scidb.for_each(@plotPerSessionPerSubject, ...
    struct('inputVal', DeltaStepLengthSymmetry(), 'colName', 'DeltaStepLengthSymmetry', 'savePath', savePath), ...
    {}, ...
    speed=["FV"], as_table=true ...
);

%% Gait speed
savePath = "Y:\LabMembers\MTillman\GitRepos\Stroke-R01-Aim-2\plots\allSubjectsAllSessions";
scidb.for_each(@plotPerSessionPerSubject, ...
    struct('inputVal', StepLengthSymmetry(), 'colName', 'StepLengthSymmetry', 'ua', UAStartFoot(), 'savePath', savePath), ...
    {}, ...
    speed=["FV"], as_table=true ...
);


%% Step length
savePath = "Y:\LabMembers\MTillman\GitRepos\Stroke-R01-Aim-2\plots\allSubjectsAllSessions";
stepLengths = GAITRiteLoadedCycle("StepLengths_GR").load(categorical=true);
sides = UAStartFoot().load(categorical=true);
stepLengthsSides = addToTable(stepLengths, sides);
stepLengthsSides = renamevars(stepLengthsSides, 'UAStartFoot', 'Side');
scidb.for_each(@plotPerSessionPerSubjectMeanDiffsPerSide, ...
    struct('inputVal', stepLengthsSides, 'colName', 'StepLengths_GR'), ...
    {}, ...
    speed=["FV"], as_table=true ...
);
