"""
Generate ready-to-paste MATLAB commands for running pipeline functions.

The generated script configures the database, registers variable types,
and calls ``scihist.for_each`` with the correct inputs, outputs, and
schema arguments — all formatted as MATLAB syntax.
"""

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def generate_matlab_command(
    function_name: str,
    db_path: str,
    schema_keys: list[str],
    variants: list[dict] | None = None,
    schema_filter: dict[str, list] | None = None,
    schema_level: list[str] | None = None,
    addpath_dirs: list[str] | None = None,
    python_executable: str | None = None,
    path_inputs: dict[str, dict] | None = None,
) -> str:
    """Generate a complete MATLAB script to run a pipeline function.

    Parameters
    ----------
    function_name
        Name of the MATLAB function to run (e.g. ``"bandpass_filter"``).
    db_path
        Absolute path to the .duckdb file.
    schema_keys
        Dataset schema keys (e.g. ``["subject", "session"]``).
    variants
        List of variant dicts from the DAG. Each variant has keys:
        ``input_types``, ``output_type``, ``constants``, ``record_count``.
        If empty/None, generates a template command.
    schema_filter
        Optional ``{key: [selected_values]}`` for filtering.
    schema_level
        Optional list of schema keys to iterate over.
    addpath_dirs
        Optional list of directories to add to MATLAB path.
    python_executable
        Optional absolute path to the Python interpreter that MATLAB's
        Python bridge should bind to. When provided, the generated script
        emits a guarded ``pyenv`` preamble that binds (or verifies) the
        interpreter before any ``py.*`` call is made. When ``None``/empty,
        no preamble is emitted (preserves behavior for non-GUI callers).

    Returns
    -------
    str
        A complete, self-contained MATLAB script.
    """
    lines: list[str] = []
    lines.append(f"%% SciStack: Run {function_name}")
    lines.append("% Generated by SciStack GUI — paste into MATLAB Command Window")
    lines.append("")

    # pyenv preamble — must come before any py.* call (i.e. before
    # scihist.configure_database, which internally calls py.scidb.*).
    if python_executable:
        lines.extend(_format_pyenv_preamble(python_executable))
        lines.append("")

    # addpath entries
    if addpath_dirs:
        for d in addpath_dirs:
            lines.append(f"addpath('{_escape_matlab_string(d)}');")
        lines.append("")

    # Configure database
    schema_keys_str = _format_matlab_string_array(schema_keys)
    lines.append("% Configure database (skip if already configured)")
    lines.append(
        f"db = scihist.configure_database('{_escape_matlab_string(db_path)}', "
        f"{schema_keys_str});"
    )
    lines.append("")

    if not variants:
        # No variant info — generate a template, but include any known path inputs.
        if path_inputs:
            inputs_str = _format_matlab_struct(
                {p: _format_path_input(pi) for p, pi in path_inputs.items()}
            )
        else:
            inputs_str = "struct()"
        lines.append("try")
        lines.append(f"    % Run (fill in inputs/outputs)")
        lines.append(f"    scihist.for_each(@{function_name}, ...")
        lines.append(f"        {inputs_str}, ...")
        lines.append(f"        {{}});")         # outputs placeholder
        lines.append("    db.close();")
        lines.append("catch scistack_err__")
        lines.append("    db.close();")
        lines.append("    rethrow(scistack_err__);")
        lines.append("end")
        return "\n".join(lines)

    # Collect all variable types referenced across all variants.
    all_var_types: set[str] = set()
    for v in variants:
        input_types = v.get("input_types", {})
        if isinstance(input_types, dict):
            all_var_types.update(input_types.values())
        output_type = v.get("output_type", "")
        if output_type:
            all_var_types.add(output_type)

    # Register variable types
    if all_var_types:
        lines.append("% Register variable types")
        for vtype in sorted(all_var_types):
            lines.append(f"scidb.register_variable('{vtype}');")
        lines.append("")

    # Deduplicate variants by constants (same logic as run.py).
    seen_constants: set[tuple] = set()
    unique_variants: list[dict] = []
    for v in variants:
        key = tuple(sorted(v.get("constants", {}).items()))
        if key not in seen_constants:
            seen_constants.add(key)
            unique_variants.append(v)

    # Wrap all for_each calls in a try/catch so db.close() always runs,
    # even if the run errors out or is interrupted.
    lines.append("try")

    # Generate for_each call for each unique variant.
    for v in unique_variants:
        input_types = v.get("input_types", {})
        output_type = v.get("output_type", "")
        constants = v.get("constants", {})

        # Build inputs struct — skip PathInput entries (handled via path_inputs).
        from scistack_gui.api.pipeline import _parse_path_input
        inputs_dict = {}
        if isinstance(input_types, dict):
            for param_name, type_name in input_types.items():
                if _parse_path_input(str(type_name)) is None:
                    inputs_dict[param_name] = f"{type_name}()"
        # Add path inputs as scifor.PathInput(...) expressions.
        if path_inputs:
            for param_name, pi in path_inputs.items():
                inputs_dict[param_name] = _format_path_input(pi)
        # Add constants as scalar values
        for k, val in constants.items():
            inputs_dict[k] = _format_matlab_value(val)

        inputs_str = _format_matlab_struct(inputs_dict)
        outputs_str = f"{{{output_type}()}}" if output_type else "{}"

        # Build schema kwargs
        iterate_keys = schema_level if schema_level else schema_keys
        schema_str = _format_schema_kwargs(
            iterate_keys, schema_filter, constants, function_name
        )

        lines.append("    % Run")
        lines.append(f"    scihist.for_each(@{function_name}, ...")
        lines.append(f"        {inputs_str}, ...")
        if schema_str:
            lines.append(f"        {outputs_str}, ...")
            lines.append(f"        {schema_str});")
        else:
            lines.append(f"        {outputs_str});")
        lines.append("")

    lines.append("    db.close();")
    lines.append("catch scistack_err__")
    lines.append("    db.close();")
    lines.append("    rethrow(scistack_err__);")
    lines.append("end")
    return "\n".join(lines)


def _format_path_input(pi: dict) -> str:
    """Format a PathInput info dict as a MATLAB ``scifor.PathInput(...)`` expression.

    The template stored in the layout may already include MATLAB double-quote
    delimiters (e.g. ``"C:\\data\\file.csv"``), or it may be a bare pattern
    string (e.g. ``{subject}/trial_{trial}.mat``). Both forms are handled.
    """
    template = pi.get("template", "")
    root_folder = pi.get("root_folder")

    # If the template is already wrapped in MATLAB double quotes, use it as-is.
    # Otherwise wrap it ourselves.
    if template.startswith('"') and template.endswith('"'):
        matlab_template = template
    else:
        matlab_template = f'"{template}"'

    if root_folder:
        return f'scifor.PathInput({matlab_template}, root_folder="{root_folder}")'
    return f"scifor.PathInput({matlab_template})"


def _escape_matlab_string(s: str) -> str:
    """Escape single quotes for MATLAB string literals."""
    return s.replace("'", "''")


def _format_pyenv_preamble(python_executable: str) -> list[str]:
    """Return MATLAB lines that bind AND force-load ``pyenv`` to the given interpreter.

    Emits three stages:
      1. Bind: if MATLAB's Python interface is ``NotLoaded``, call
         ``pyenv('Version', python_executable)``. If it is already loaded but
         points to a different interpreter, ``error`` out with
         ``SciStack:PyenvMismatch``.
      2. Force-load: call ``py.sys.version`` (a trivial Python call) inside
         a try/catch. This is required because ``pyenv('Version', ...)`` only
         *configures* Python; it does not actually load it. On some
         MATLAB+venv combinations, the first ``py.*`` call inside a package
         function (e.g. ``scihist.configure_database``) fails with
         "Unrecognized function or variable 'py'" because MATLAB's symbol
         resolver runs before the Python load. Loading Python here — from
         the script's top-level scope — avoids that path entirely.
      3. Diagnostic dump on failure: print MATLAB's ``pyenv`` state to
         stderr and suggest the ``'ExecutionMode', 'OutOfProcess'``
         workaround, then rethrow so the user sees the underlying MATLAB
         error.

    The path is converted to forward slashes (matching ``matlabTerminal.ts``
    convention for MATLAB single-quoted string literals on Windows) and
    single quotes are escaped via ``_escape_matlab_string``.

    Temporary variables use a ``scistack_*__`` namespace suffix and are
    ``clear``ed at the end so the script doesn't leak state into the
    caller's workspace (``run(...)`` evaluates in caller scope).
    """
    # Normalize backslashes (Windows) to forward slashes for the MATLAB literal.
    normalized = python_executable.replace("\\", "/")
    escaped = _escape_matlab_string(normalized)
    return [
        "% Bind MATLAB's Python interface to the scistack-gui interpreter.",
        f"scistack_pyenv_target__ = '{escaped}';",
        "scistack_pyenv__ = pyenv;",
        "% Normalize path separators (MATLAB returns `\\`, our target uses `/`)",
        "% and compare case-insensitively (Windows paths are case-insensitive;",
        "% MATLAB may lowercase what it stores).",
        "scistack_norm_path__ = @(p) strrep(char(p), '\\', '/');",
        'if scistack_pyenv__.Status == "NotLoaded"',
        "    scistack_pyenv__ = pyenv('Version', scistack_pyenv_target__);",
        "elseif ~strcmpi(scistack_norm_path__(scistack_pyenv__.Executable), ...",
        "                scistack_norm_path__(scistack_pyenv_target__))",
        "    error('SciStack:PyenvMismatch', ...",
        "        'MATLAB already loaded Python %s; restart MATLAB to switch to %s.', ...",
        "        scistack_pyenv__.Executable, scistack_pyenv_target__);",
        "end",
        "% Force Python to actually load NOW (at script top-level), so that",
        "% subsequent py.* calls inside package functions (e.g.",
        "% scihist.configure_database) resolve correctly. pyenv('Version', ...)",
        "% only configures Python; it does not load it.",
        "try",
        "    scistack_py_version__ = char(py.sys.version);",
        "    fprintf('[SciStack] Python loaded: %s (%s)\\n', ...",
        "        char(scistack_pyenv__.Executable), strtrim(scistack_py_version__));",
        "catch scistack_py_err__",
        "    fprintf(2, '[SciStack] py.sys.version failed: %s\\n', scistack_py_err__.message);",
        "    fprintf(2, ['[SciStack] pyenv state: Status=%s Version=%s ' ...",
        "        'Executable=%s Library=%s ExecutionMode=%s\\n'], ...",
        "        string(scistack_pyenv__.Status), string(scistack_pyenv__.Version), ...",
        "        string(scistack_pyenv__.Executable), string(scistack_pyenv__.Library), ...",
        "        string(scistack_pyenv__.ExecutionMode));",
        "    fprintf(2, ['[SciStack] Workaround to try: pyenv(''Version'', ''%s'', ' ...",
        "        '''ExecutionMode'', ''OutOfProcess''); py.sys.version\\n'], ...",
        "        scistack_pyenv_target__);",
        "    rethrow(scistack_py_err__);",
        "end",
        "% Pre-import the scidb module so py.scidb.* is warm, and so we can",
        "% distinguish 'py dispatch broken inside functions' from 'scidb module",
        "% not importable' when debugging.",
        "try",
        "    py.importlib.import_module('scidb');",
        "    fprintf('[SciStack] py.scidb import OK\\n');",
        "catch scistack_import_err__",
        "    fprintf(2, '[SciStack] py.importlib.import_module(''scidb'') failed: %s\\n', ...",
        "        scistack_import_err__.message);",
        "    rethrow(scistack_import_err__);",
        "end",
        "clear scistack_pyenv__ scistack_pyenv_target__ scistack_norm_path__ ...",
        "    scistack_py_version__ scistack_py_err__ scistack_import_err__;",
    ]


def _format_matlab_value(val) -> str:
    """Format a Python value as a MATLAB literal."""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, int):
        return str(val)
    if isinstance(val, float):
        return str(val)
    if isinstance(val, str):
        return f"'{_escape_matlab_string(val)}'"
    if isinstance(val, (list, tuple)):
        elements = [_format_matlab_value(v) for v in val]
        return f"[{', '.join(elements)}]"
    return f"'{_escape_matlab_string(str(val))}'"


def _format_matlab_struct(inputs_dict: dict[str, str]) -> str:
    """Build a MATLAB ``struct(...)`` expression from a dict.

    Values are already formatted as MATLAB expressions (not quoted again).
    """
    if not inputs_dict:
        return "struct()"
    pairs = []
    for k, v in inputs_dict.items():
        pairs.append(f"'{k}', {v}")
    return f"struct({', '.join(pairs)})"


def _format_matlab_cell(items: list[str]) -> str:
    """Build a MATLAB cell array ``{Item1(), Item2()}``."""
    return "{" + ", ".join(items) + "}"


def _format_matlab_string_array(items: list[str]) -> str:
    """Format a Python list of strings as a MATLAB string array ``["a", "b"]``."""
    if not items:
        return "[]"
    escaped = [f'"{_escape_matlab_string(s)}"' for s in items]
    return "[" + ", ".join(escaped) + "]"


def _format_schema_kwargs(
    iterate_keys: list[str],
    schema_filter: dict[str, list] | None,
    constants: dict,
    function_name: str,
) -> str:
    """Build MATLAB name-value schema keyword arguments for for_each.

    Returns empty string if there are no schema arguments to pass.
    """
    if not iterate_keys:
        return ""

    parts = []
    for key in iterate_keys:
        if schema_filter and key in schema_filter and schema_filter[key]:
            values = schema_filter[key]
            # Format values: numbers as array, strings as string array.
            if all(isinstance(v, (int, float)) for v in values):
                formatted = "[" + " ".join(str(v) for v in values) + "]"
            else:
                formatted = _format_matlab_string_array([str(v) for v in values])
            parts.append(f"'{key}', {formatted}")

    if not parts:
        return ""
    return ", ".join(parts)
